name: driving-test-qcm-ar
region: nyc

static_sites:
  - name: web
    github:
      repo: hadikoub/Lebanese-Driving-License-Web-App
      branch: main
      deploy_on_push: true
    source_dir: /
    environment_slug: node-js
    build_command: npm ci && npm run build
    output_dir: dist
    index_document: index.html
    catchall_document: index.html
    routes:
      - path: /
